project_id = "yudkfmgilucyhukfggij"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.generate-study-plan]
    verify_jwt = false
  [functions.study-buddy]
    verify_jwt = false
  [functions.analyze-behavior]
    verify_jwt = false
  [functions.compute-question-tiers]
    verify_jwt = false
