#!/usr/bin/env python3
"""Builds migrations_v2/0050_pie_p3_seed_lo_map_irt.sql and review CSVs from:
   live_question_templates.json (read-only SELECT from V2, 7 Oct 2026), lo_definitions.json,
   and the qbank (irt_b by zyntra_id/external_ref). Deterministic; re-run to regenerate."""
import json, re, csv, glob, os, sys, uuid
here = os.path.dirname(os.path.abspath(__file__))
root = os.path.abspath(os.path.join(here, '..', '..', '..'))
rows = json.load(open(os.path.join(here, 'live_question_templates.json')))
defs = json.load(open(os.path.join(here, 'lo_definitions.json')))
qbank_dir = os.environ.get('QBANK_DIR', '/home/box/zyntra/qbank')
NS = uuid.UUID('6a1f0d1e-6f0e-4c8b-9d7e-5049e3a10000')

def key(s): return re.sub(r'[^A-Z0-9]+', '_', s.upper()).strip('_')

qb = {}
for f in sorted(glob.glob(os.path.join(qbank_dir, 'batch*/batch*.json'))):
    if 'upload' in f: continue
    for it in json.load(open(f)):
        if it.get('irt_b') in (None, '', 'None'): continue
        for k in (it.get('id'), it.get('external_ref'), it.get('zyntra_id')):
            if k: qb[k] = (float(it['irt_b']), it.get('irt_b_source') or 'author_estimate', os.path.relpath(f, qbank_dir))

prior = {k: v for k, v in defs['irt_b_tier_prior'].items() if not k.startswith('_')}
q = lambda s: "'" + s.replace("'", "''") + "'"
concepts, los, maps, irt, review = [], [], [], [], []
unmatched_tier = 0; qb_hits = 0
for r in rows:
    sub = r['subtopic']; subj = r['subject']
    title, flag = defs['los'][sub]
    ck = f"{key(subj)}.{key(sub)}"; lk = f"{ck}.LO1"
    cid = uuid.uuid5(NS, 'concept:' + ck); lid = uuid.uuid5(NS, 'lo:' + lk)
    concepts.append(f"({q(str(cid))}::uuid,{q(ck)},{q(sub)},{q('Subject: ' + subj)})")
    los.append(f"({q(str(lid))}::uuid,{q(lk)},{q(str(cid))}::uuid,{q(title)},{q('Stem template: ' + r['template'])})")
    for it in r['items']:
        maps.append(f"({q(it['id'])}::uuid,{q(str(lid))}::uuid)")
        if it['zid'] in qb:
            b, src, f = qb[it['zid']]; qb_hits += 1
            irt.append(f"({q(it['id'])}::uuid,{b},0.5,'qbank_import',{q(src + ' ' + f)})")
        elif it['tier'] in prior:
            irt.append(f"({q(it['id'])}::uuid,{prior[it['tier']]},1.0,'tier_prior',{q('tier=' + it['tier'])})")
        else:
            unmatched_tier += 1
        review.append({'zyntra_id': it['zid'], 'question_id': it['id'], 'subject': subj, 'concept_key': ck, 'lo_key': lk,
                       'tier': it['tier'], 'irt_b_source': 'qbank_import' if it['zid'] in qb else 'tier_prior',
                       'mapping_confidence': 'low' if flag else 'high', 'review_note': flag or ''})

sql = f"""-- 0050: P3 seed - concept/LO definitions, question->LO map and irt_b for the 225 live V2
-- questions. GENERATED by supabase/seed_v2/pie_p3/build_seed.py from a read-only SELECT of
-- live V2 (7 Oct 2026). Do not hand-edit; regenerate.
-- Mapping: concept = subtopic, one LO per stem template ({len(los)} LOs, {len(maps)} mappings).
-- Low-confidence mappings ({sum(1 for x in review if x['mapping_confidence']=='low')} questions) are flagged in
-- pie.question_lo.mapping_source = 'pending_clinician_review' (see lo_map_review.csv).
-- irt_b: qbank matches by zyntra_id = {qb_hits}; all others use the documented tier prior
-- (source 'tier_prior', se 1.0, uncalibrated DESIGN DEFAULT).
alter table pie.question_lo drop constraint if exists question_lo_mapping_source_check;
alter table pie.question_lo add constraint question_lo_mapping_source_check
  check (mapping_source in ('manual','import','model_suggested_reviewed','pending_clinician_review'));
alter table public.questions drop constraint if exists questions_irt_b_source_check;
alter table public.questions add constraint questions_irt_b_source_check
  check (irt_b_source is null or irt_b_source in ('expert_prior','qbank_import','calibrated','tier_prior'));
alter table public.questions add column if not exists irt_b_note text;
revoke all (irt_b_note) on public.questions from public, anon, authenticated;

insert into pie.concept(id, concept_key, title, description) values
{(','+chr(10)).join(concepts)}
on conflict (concept_key) do nothing;

insert into pie.learning_objective(id, lo_key, concept_id, title, description) values
{(','+chr(10)).join(los)}
on conflict (lo_key) do nothing;

-- Only questions that exist (the seed is safe on a DB without the live content).
insert into pie.question_lo(question_id, lo_id, is_primary, weight, mapping_source)
select m.qid, m.lid, true, 1, 'import'
from (values
{(','+chr(10)).join(maps)}
) m(qid, lid)
join public.questions qq on qq.id = m.qid
on conflict (question_id, lo_id) do nothing;

update pie.question_lo ql set mapping_source = 'pending_clinician_review'
from pie.learning_objective lo
where lo.id = ql.lo_id and lo.lo_key in ({', '.join(sorted({q(x['lo_key']) for x in review if x['mapping_confidence']=='low'}))});

update public.questions qq set irt_b = v.b, irt_b_se = v.se, irt_b_source = v.src, irt_b_note = v.note
from (values
{(','+chr(10)).join(irt)}
) v(qid, b, se, src, note)
where qq.id = v.qid and qq.irt_b is null;
"""
out = os.path.join(root, 'supabase', 'migrations_v2', '0050_pie_p3_seed_lo_map_irt.sql')
open(out, 'w').write(sql)
with open(os.path.join(here, 'lo_map_review.csv'), 'w', newline='') as fh:
    w = csv.DictWriter(fh, fieldnames=list(review[0].keys())); w.writeheader(); w.writerows(review)
print(f"concepts={len(concepts)} los={len(los)} maps={len(maps)} irt={len(irt)} qbank_hits={qb_hits} unmatched_tier={unmatched_tier} low_conf={sum(1 for x in review if x['mapping_confidence']=='low')}")
